package pl.softra.swingtutorial;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.io.File;

/**
 * Created by erykmariankowski on 26.07.2018.
 */
public class RootController {
    private final DefaultListModel<File> model;
    private JPanel rootPanel;
    private JList fileList;

    @SuppressWarnings("unchecked")
    RootController() {
        model = new DefaultListModel<>();
        model.addElement(new File("~/dupa.war"));
        model.addElement(new File("~/dupa2.war"));
        fileList.setCellRenderer(new FileRenderer());
        fileList.setModel(model);
        fileList.setDropMode(DropMode.INSERT);
        fileList.setDragEnabled(true);
        fileList.setTransferHandler(new ListItemTransferHandler(files -> {
            for (File file : files) {
                model.addElement(file);
            }
        }));
    }

    JPanel getRootPanel() {
        return rootPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.setBorder(BorderFactory.createTitledBorder("Example list"));
        final JScrollPane scrollPane1 = new JScrollPane();
        rootPanel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        fileList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        fileList.setModel(defaultListModel1);
        scrollPane1.setViewportView(fileList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
